### ISSUE TITLE
checkX13binary chokes on spaces in file path

### ISSUE THREAD

**Issue by lukeanker** [cran/x13binary#1]
`checkX13binary()`

leads to

```
Error in checkX13binary() : When running

  C:/Program Files/R/R-3.1.1/library/x13binary/bin/x13ashtml.exe

Command Prompt returned the following message:

  Der Befehl "C:/Program" ist entweder falsch geschrieben oder
  konnte nicht gefunden werden.

In addition: Warning message:
running command 'C:\Windows\system32\cmd.exe /c C:/Program Files/R/R-3.1.1/library/x13binary/bin/x13ashtml.exe C:\Windows\TEMP\RtmpKEpBPO/Testairline' had status 1
```

_(Translation: The command c:/Program is either spelled wrong or could not be found.)_

Wrapping `x13.bin` in quotes works: 

`system(paste0('"', x13.bin, '" ', file.path( tdir, "Testairline")))`

I'm on  Windows 7 x64.

**Comment by gaborcsardi** [comment]
Hello, this is a read-only mirror of CRAN. Please report issues to the package maintainer. See the DESCRIPTION file.

**Comment by lukeanker** [comment]
Oops, thanks I'll do that.
